services:

  api:
    build:
      context: ./server
      dockerfile: DockerFile.api
    ports:
      - "2405:2405"
    depends_on:
      - redis
    env_file:
      - ./server/.env

  worker:
    build:
      context: ./server
      dockerfile: DockerFile.worker
    depends_on:
      - redis
    env_file:
      - ./server/.env

  redis:
    image: redis:7
    ports:
      - "6379:6379"
